name: test using geth

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Geth Action
        uses: odanado/geth-action@v0.0.8
        id: geth

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: run build
        run: |
          yarn build
        env:
          RPC_URL: ${{ steps.geth.outputs.rpc_url }}
          PRIVATE_KEY: ${{ steps.geth.outputs.private_key }}


      - name: run test
        run: |
          yarn truffle test --network private
        env:
          RPC_URL: ${{ steps.geth.outputs.rpc_url }}
          PRIVATE_KEY: ${{ steps.geth.outputs.private_key }}
